---
name: Test-algorithm
author: xiaoxuan
version: 1
description: Discover petri nets using alpha.

services:
  Test_alpha_Container:
    image: python:3.9
    build:
      context: .    # 确保context路径正确，即使Dockerfile在项目的当前目录
    volumes:
      - ./data:/app/data      # 将当前目录挂载到容器的/app目录
  Test_inductive_Container:
    image: python:3.9
    build:
      context: .
    volumes:
      - ./data:/app/data
  Test_heuristics_Container:
    image: python:3.9
    build:
      context: .
    volumes:
      - ./data:/app/data
  Test_ilp_Container:
    image: python:3.9
    build:
      context: .
    volumes:
      - ./data:/app/data

flow:
  - name: Test alpha
    container: Test_alpha_Container
    commands:
      - type: console
        command: python /app/algorithm.py alpha
        note: Running alpha
  - name: Test inductive
    container: Test_inductive_Container
    commands:
      - type: console
        command: python /app/algorithm.py inductive
        note: Running inductive
  - name: Test heuristics
    container: Test_heuristics_Container
    commands:
      - type: console
        command: python /app/algorithm.py heuristics
        note: Running heuristics
  - name: Test ilp
    container: Test_ilp_Container
    commands:
      - type: console
        command: python /app/algorithm.py ilp
        note: Running ilp

